apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: sportapps-ns
  labels:
    app: front
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: fe-hpa
  namespace: sportapps-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: 60
  - type: Resource
    resource:
     name: memory
     target:
       type: Utilization
       averageValue: 800Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: sportapps-ns
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 0.7Gi
      tolerations:
      - key: instance_type
        value: spot
        effect: NoSchedule
        operator: Equal
