name: SonarCloud Front analysis
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Cache node modules
        id: node-cache # Id del cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run Build command
        run: npm run build -- --prod
      - name: Run Unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
      - name: Run Coverage
        run: npm run coverage -- --watch=false --browsers=ChromeHeadless
      - name: Cat before info
        run: cat ./coverage/lcov.info
      - name: Seed lcov
        run: sed -i 's+/home/runner/work/SportAppsFront/SportAppsFront/++g' coverage/lcov.info
      - name: Cat after info
        run: cat ./coverage/lcov.info
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=Grupo5Uniandes2022_SportAppsFront
            -Dsonar.organization=grupo5uniandes2022
            -Dsonar.language=js
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.test.exclusions=**/node_modules/**,src/assets/**
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.typescript.tsconfigPaths=tsconfig.json
